### PR TITLE
WIP: feat: setup pipeline graph

### PR DESCRIPTION
**Pull request by garrettmichaelgeorge**
Add basic functionality to set up a directed acyclic graph for describing a run's pipelines.

For any given pipeline, users can specify `"depends_on": my_pipeline_name` in the config file, and the pipeline will be set up automatically.

See `run_test.exs` for example usage.

Note this is a WIP  😃.

### CODE REVIEW

**Comment by garrettmichaelgeorge** [comment]
Note I branched this off of #7 to get the latest features – we will need to wait until that PR is merged to `master`, then merge in the upstream changes here, before finally merging this one.

**Comment by garrettmichaelgeorge** [comment]
I used `run.pipeline_graph` as a placeholder name since some tests depend on `run.pipelines` still, leaving us in the interim with `run.pipelines` and `run.pipeline_graph`.

I think the goal should be to replace the `run.pipelines` implementation with the graph one, so there would be only `run.pipelines`, and the caller should not know one way or the other.

I'll work on this.

**Comment by garrettmichaelgeorge** [comment]
> I think the goal should be to replace the `run.pipelines` implementation with the graph one, so there would be only `run.pipelines`, and the caller should not know one way or the other.
> 
> I'll work on this.

Done. `run.pipelines` now uses the graph implementation under the hood. All previous tests pass, as do the new ones. Treating `run.pipelines` like an opaque datatype and relying on public functions like `Run.pipelines(my_run)` or `Run.put_pipeline/3` made this possible. 

If we don't end up liking libgraph for whatever reason, I think it should be fairly straightforward to swap it out now, as its usage is contained to the bodies of public functions in `ExIntegrate.Core.Run` and doesn't leak outside of those places.

**Comment by garrettmichaelgeorge** [comment]
@samrose I think this is ready to merge. The main goal was to implement the core data operations that OTP modules will use when interacting with a run. This PR should get us up and running, and when we inevitably discover more operations to add, we can do so on a case by case basis.

But overall, as far as I can tell, I think we're ready to merge this and start experimenting with the boundary OTP servers.

**Review by samrose — APPROVED** [review]

**Pull request merged**
