### PR TITLE
feat: reduce nix to using niv

### PR DESCRIPTION
**Pull request by samrose**
This PR switches us from tracking local `*.nix` files, to using niv as a convention, and following their usage guidelines https://github.com/nmattia/niv

the steps I followed were to

- `nix-shell -p niv`
- `niv update nixpkgs -b master` to get on the current master branch of nixpkgs, which has the latest releases of elixir and erlang
- `exit` this shell
- once that process is completed, this example shell.nix file works and all tests pass on ex_integrate https://gist.github.com/samrose/55e6fa28fd7fc0498678c3dffc53b363

I chose to remove all nix files not found in the `nix/` dir, and to gitignore `shell.nix` in the `.gitignore` file so that we could then import these deps, and create our own custom shell nix with these deps (with our preferred file watching, neovim config etc)

We could also create instructions in readme or elsewhere on creating a shell nix to run the app in development mode.

### CODE REVIEW

**Comment by garrettmichaelgeorge** [comment]
@samrose Thanks for putting this together!

Would we also want to utilize niv/nix in our CircleCI config, since we also specify Elixir/Erlang versions there? Or is this still for local dev only? I've been thinking lately about how best to support multiple versions of Elixir/Erlang upon release, and wonder if niv/nix would play into it.

**Comment by garrettmichaelgeorge** [comment]
Some resources from our discussion:
* http://ghedam.at/15443/a-nix-shell-for-developing-elixir
* https://rgoswami.me/posts/ccon-tut-nix/#project-setup

**Comment by garrettmichaelgeorge** [comment]
@samrose When I ran `niv update nixpkgs -b master`, it appears `nix/sources.json` was altered to match the latest Nix master. How should we handle that file given that it is under version control? Do we need to check it in each time we run the above command?

**Review by garrettmichaelgeorge — CHANGES_REQUESTED** [review]
I'm excited about this change! Thanks so much for doing the work to get niv set up.

We might as well take the opportunity to update the README with the text and setup steps from your PR description, and an example `shell.nix` drawn from our two versions.

**Comment by garrettmichaelgeorge** [comment]
> @garrettmichaelgeorge you can `git reset --hard HEAD` OR `niv update nixpkgs -r 2211a7cf7498ec326fa66cb81e4cdb2c5a07b10c` get back to the specific content that was in the `nix/sources.json` and then in future we would only `niv update nixpkgs -b master` or to revision if we want to bump the nixpkgs version if that makes sense?

Ah I see, this is the means by which niv pins dependency versions – thank you.

So for an initial installation on a fresh clone of this repo, should we omit the `niv update nixpkgs -b master` step? I assume we want contributors developing against the pinned versions of Elixir and Erlang, not the latest, since the pinned versions should match what will run in CI, etc. Am I understanding this correctly?

**Comment by samrose** [comment]
I think we addressed your requested changes @garrettmichaelgeorge if not let me know what I am missing here. Thanks!

**Comment by samrose** [comment]
I am adding elixir.nix and erlang.nix here + example of how to use in shell.nix and then this should be set

**Comment by garrettmichaelgeorge** [comment]
Closes #47.

**Comment by samrose** [comment]
@garrettmichaelgeorge can you re-review it now?

Also I will make a new issue to use this new set up to create docker images for circleci as well. But didn't want to hold this up with that.

**Review by garrettmichaelgeorge — APPROVED** [review]
Thanks so much, @samrose! Everything runs on my machine. It's great that we can continue pinning Erlang and Elixir versions.

I did have to update my `shell.nix` to import the pinned `nix/elixir.nix` and `nix/erlang.nix` – the import lines are in my comment below. 

Aside from adding those lines to the example `shell.nix`, I think we're all set!

**Comment by samrose** [comment]
@garrettmichaelgeorge oh man sorry thanks for calling that out. I will include your change you are totally correct

**Pull request merged**
