### PR TITLE
updating respective files to use elixir 1.13.0

### PR DESCRIPTION
**Pull request by samrose**

### CODE REVIEW

**Comment by samrose** [comment]
@garrettmichaelgeorge review requested

**Comment by garrettmichaelgeorge** [comment]
@samrose when I tried running the branch locally, I got:

```
$ mix test
** (Mix) You're trying to run :ex_integrate on Elixir v1.12.3 but it has 
declared in its mix.exs file it supports only Elixir ~> 1.13
```

Of course this is because I was using `my_shell.nix` rather than `shell.nix`, which was updated in this PR. I can change my `my_shell.nix` to match, but it might be worth considering how we can improve developer experience around this. 

Maybe there is some way of allowing individual Nix shell configs while still keeping in sync with the current branch's `shell.nix`? I feel like this sort of "oops" moment would happen to contributors each time `shell.nix` is changed.

**Comment by garrettmichaelgeorge** [comment]
> Maybe there is some way of allowing individual Nix shell configs while still keeping in sync with the current branch's `shell.nix`

Actually I was wrong – since the Elixir version is kept in `elixir.nix`, it is already being imported into both `shell.nix` and `my_shell.nix`. So I think the current setup nicely allows for the above.

Which makes me wonder why my Nix shell is still loading Elixir 1.12.3:

```
$ which elixir
/nix/store/fzhqh72fzfg9nnlh0n612qkx3d8k4kgn-elixir-1.12.3/bin/elixir
```

**Comment by samrose** [comment]
> @samrose when I tried running the branch locally, I got:
> 
> ```
> $ mix test
> ** (Mix) You're trying to run :ex_integrate on Elixir v1.12.3 but it has 
> declared in its mix.exs file it supports only Elixir ~> 1.13
> ```
> 
> Of course this is because I was using `my_shell.nix` rather than `shell.nix`, which was updated in this PR. I can change my `my_shell.nix` to match, but it might be worth considering how we can improve developer experience around this.
> 
> Maybe there is some way of allowing individual Nix shell configs while still keeping in sync with the current branch's `shell.nix`? I feel like this sort of "oops" moment would happen to contributors each time `shell.nix` is changed.

What I've been doing is using imports in my shell.nix, and then only using the "official" erlang.nix and elixir.nix that we release

However, I would like to really resolve this once and for all sometime this week. You and I could discuss this in chat.

I think the reason I suggested creating a `myshell.nix` was to deal with unique local neovim differences. One of the problems I ran into and did not have time to investigate was how to only import a file if present. There is probably a way to do this. So that we could document a way that a user could create a `neovim.nix` and inside of that also consume a `.vimrc` for the shell, gitignore these, etc

I just need to have some time to research this, and test and implement  a solution

**Comment by garrettmichaelgeorge** [comment]
@samrose all makes sense, thank you. My mistake – I had forgotten to reload [direnv](https://nix.dev/tutorials/declarative-and-reproducible-developer-environments#direnv-automatically-activating-the-environment-on-directory-change) as it had cached the previous Nix shell config. Everything in the PR looks great to me! 👍

**Review by garrettmichaelgeorge — APPROVED** [review]

**Pull request merged**
