### PR TITLE
feat: define core modules and basic workflow

### PR DESCRIPTION
**Pull request by garrettmichaelgeorge**
- [x] refactor: import config file into a Config structure
- [x] feat: update the Config structure to include pipelines as parents of steps
  - this will probably require extracting a `%Pipeline{}` to house the steps, so a Config has many Pipelines, and a Pipeline has many Steps
  - @samrose if I am messing up the DAG model, let me know! this may be the time to get that ironed out, at least initially. I think the JSON that I tried at the end was forcing it into a tree structure which could be problematic. Maybe the question is: how does one represent a DAG in JSON?
- [x] figure out Pipelines and define the next steps…

### CODE REVIEW

**Comment by garrettmichaelgeorge** [comment]
@samrose Implemented basic error handling, accounting for both nonzero status errors and Rambo errors. The main function now returns `{:error, error}` if any step in any pipeline errors out.

It does not yet stop running a pipeline's steps or react in any other way. But the logic to catch errors in a basic way is now there.

See the new test that runs a bash script that exits with 1.

**Comment by garrettmichaelgeorge** [comment]
@samrose Also we should perhaps consider whether to merge this to `master` and continue in this vein with additional PRs. Is there anything else you would like to see from this PR?

(I suppose "First Use Case" is a vague name – perhaps this PR could be called something like "feat: parse config and catch step errors.")

**Comment by garrettmichaelgeorge** [comment]
@samrose I removed the `Task` wrapper while running steps and replaced it instead with a simple `Enum.reduce/3`. From the perspective of a pipeline (a core module), all that is happening is manipulation of data structures. Hopefully this will help enforce separation of concerns.

We can put the OTP wrapper behaviour instead in a separate boundary module.

**Comment by garrettmichaelgeorge** [comment]
Also, the `Rambo` data is now unpacked and stored in each `Step` after running.

**Comment by garrettmichaelgeorge** [comment]
Output of running `ei.json`:

```
iex(1)> ExIntegrate.run_pipelines_from_file "ei.json"
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  jason 1.2.2
  rambo 0.3.4
All dependencies are up to date
Compiling 5 files (.ex)
Generated ex_integrate app
Compiling 5 files (.ex)
Generated ex_integrate app
...This is an error
                   .

Finished in 0.1 seconds (0.00s async, 0.1s sync)
4 tests, 0 failures

Randomized with seed 373777
{:ok,
 %ExIntegrate.Config{
   pipelines: [
     %ExIntegrate.Pipeline{
       completed_steps: [
         %ExIntegrate.Step{
           args: ["compile"],
           command: "mix",
           err: "",
           name: "compile",
           out: "Compiling 5 files (.ex)\nGenerated ex_integrate app\n",
           status: 0
         },
         %ExIntegrate.Step{
           args: ["clean"],
           command: "mix",
           err: "",
           name: "clean",
           out: "",
           status: 0
         },
         %ExIntegrate.Step{
           args: ["deps.get"],
           command: "mix",
           err: "",
           name: "get deps",
           out: "Resolving Hex dependencies...\nDependency resolution completed:\nUnchanged:\n  jason 1.2.2\n  rambo 0.3.4\nAll dependencies are up to date\n",
           status: 0
         } |
         nil
       ],
       failed?: nil,
       remaining_steps: nil,
       steps: [
         %ExIntegrate.Step{
           args: ["deps.get"],
           command: "mix",
           err: nil,
           name: "get deps",
           out: nil,
           status: :not_run
         },
         %ExIntegrate.Step{
           args: ["clean"],
           command: "mix",
           err: nil,
           name: "clean",
           out: nil,
           status: :not_run
         },
         %ExIntegrate.Step{
           args: ["compile"],
           command: "mix",
           err: nil,
           name: "compile",
           out: nil,
           status: :not_run
         }
       ]
     },
     %ExIntegrate.Pipeline{
       completed_steps: [
         %ExIntegrate.Step{
           args: ["test"],
           command: "mix",
           err: "This is an error\n",
           name: "compile",
           out: "Compiling 5 files (.ex)\nGenerated ex_integrate app\n....\n\nFinished in 0.1 seconds (0.00s async, 0.1s sync)\n4 tests, 0 failures\n\nRandomized with seed 373777\n",
           status: 0
         } |
         nil
       ],
       failed?: nil,
       remaining_steps: nil,
       steps: [
         %ExIntegrate.Step{
           args: ["test"],
           command: "mix",
           err: nil,
           name: "compile",
           out: nil,
           status: :not_run
         }
       ]
     }
   ]
 }}
```

**Comment by garrettmichaelgeorge** [comment]
You'll notice this line: `err: "This is an error\n",` This is the stderr output from the test fixture bash script that prints to stderr. 

Apparently when ExIntegrate's test suite gets run via `ei.json`, it prints to stderr as expected. This then gets picked up by Rambo and stored in ExIntegrate's output.

Do you consider this a feature or a bug? @samrose

**Review by samrose — APPROVED** [review]

**Comment by samrose** [comment]
@garrettmichaelgeorge are you ok with merging this into master now?

**Comment by garrettmichaelgeorge** [comment]
> @garrettmichaelgeorge are you ok with merging this into master now?

@samrose yes I think it's good enough for now. Everything behaves as it's expected to. We can refine further in other PRs.

**Comment by garrettmichaelgeorge** [comment]
@samrose Feel free to merge or squash as you like.

**Comment by samrose** [comment]
@garrettmichaelgeorge done thanks!

**Pull request merged**
